### ISSUE TITLE
Is this package used anywhere?

### ISSUE THREAD

**Issue by dmitshur** [tsileo/indieauth#1]
Hi there,

Thanks for making a Go package for IndieAuth! I’m glad I found it.

I am wondering whether it’s being used anywhere? I’m not seeing any importers on godoc.org:

https://godoc.org/a4.io/go/indieauth?importers

Thanks!

**Comment by tsileo** [comment]
Closing this, but in case anyone is still interested, you can see a public example in [BlobStash](https://github.com/tsileo/blobstash), but the use case is a bit complex.

Thanks!
